"""followers

Revision ID: 77a93441c0e9
Revises: 38215f763828
Create Date: 2019-08-04 23:19:49.428660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a93441c0e9'
down_revision = '38215f763828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
