"""add version

Revision ID: accfc6a50754
Revises: dfa6bb363dd2
Create Date: 2019-06-11 13:28:57.865758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accfc6a50754'
down_revision = 'dfa6bb363dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=14), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('from_versions', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_date'), 'release', ['date'], unique=False)
    op.create_index(op.f('ix_release_timestamp'), 'release', ['timestamp'], unique=False)
    op.create_index(op.f('ix_release_version'), 'release', ['version'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_version'), table_name='release')
    op.drop_index(op.f('ix_release_timestamp'), table_name='release')
    op.drop_index(op.f('ix_release_date'), table_name='release')
    op.drop_table('release')
    # ### end Alembic commands ###
