"""Configuration table

Revision ID: dfa6bb363dd2
Revises: 
Create Date: 2019-05-31 00:56:22.951156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa6bb363dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('edition', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_description'), 'configuration', ['description'], unique=True)
    op.create_index(op.f('ix_configuration_name'), 'configuration', ['name'], unique=False)
    op.create_index(op.f('ix_configuration_project'), 'configuration', ['project'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuration_project'), table_name='configuration')
    op.drop_index(op.f('ix_configuration_name'), table_name='configuration')
    op.drop_index(op.f('ix_configuration_description'), table_name='configuration')
    op.drop_table('configuration')
    # ### end Alembic commands ###
